# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=50)),
                ('hair_length', models.CharField(max_length=50)),
                ('life_span', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50)),
                ('gender', models.BooleanField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('pet_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petdogs.BreedInfo')),
            ],
        ),
    ]
