# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petdogs', '0003_auto_20171101_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petinfo',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='petinfo',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
