# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petdogs', '0004_auto_20171101_1850'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BreedInfo',
            new_name='DogBreedInfo',
        ),
        migrations.RenameModel(
            old_name='PetInfo',
            new_name='DogInfo',
        ),
    ]
